- businesscentral/image.yaml
- controller/image.yaml
- kieserver/image.yaml
- smartrouter/image.yaml
https://issues.jboss.org/browse/CLOUD-2235
The KIE modules are moving from cct_module to the jboss-kie-modules
repository. Add this to our list of module repositories.
> CLOUD-2235 add jboss-kie-modules module repository

- templates/rhba70-businesscentral-monitoring-with-smartrouter.yaml
- templates/rhba70-businesscentral-monitoring.yaml
- templates/rhba70-businesscentral.yaml
- templates/rhba70-full-mysql.yaml
- templates/rhba70-kieserver-basic-s2i.yaml
- templates/rhba70-kieserver-externaldb.yaml
- templates/rhba70-kieserver-https-s2i.yaml
- templates/rhba70-kieserver-postgresql.yaml
https://issues.jboss.org/browse/RHBA-577
> [RHBA-577] Create OpenShift templates based on RHBA LA release -- 1st draft

- templates/rhpam70-authoring.yaml
https://issues.jboss.org/browse/RHBA-724
> [RHBA-724] Added rhpam70-authoring template

- templates/rhpam70-trial-ephemeral.yaml
https://issues.jboss.org/browse/RHBA-724
> [RHBA-724] Added rhpam70-trial-ephemeral template

- templates/rhpam70-prod-immutable-monitor.yaml
- templates/rhpam70-sit.yaml
When using Business Central Monitoring, there is no authoring and no data to be persisted. However, the controller configuration must persist to not disconnect from KIE servers on a pod restart.
> [RHPAM-731] Persist business central monitoring controller configuration

- templates/rhpam70-authoring.yaml
- templates/rhpam70-prod-immutable-monitor.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
- templates/rhpam70-trial-ephemeral.yaml
Signed-off-by: calvin zhu <calvinzhu@hotmail.com>
> [RHPAM-263] fix for Liveness probe for Business Central

- kieserver/image.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
> [RHPAM-794] - Allow KIE server / OpenShift to be completely immutable

- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
Include the POSTGRESQL_MAX_PREPARED_TRANSACTIONS env on the templates that uses POstgreSQL server.
> [RHPAM-181] - Kie server timers aren't clustered

- businesscentral-indexing/image.yaml
- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- controller/image.yaml
- kieserver/image.yaml
- smartrouter/image.yaml
[RHPAM-1173] rhpam70-dev branch should use CE sprint-18
https://issues.jboss.org/browse/RHPAM-1173
> [RHPAM-1173] rhpam70-dev branch should use CE sprint-18

- templates/rhpam70-kieserver-externaldb.yaml
Added parameter to allow configuration of database port
> [RHPAM-1178] EJB Timer Datasource only works for MySQL with default port

- templates/docs/rhpam70-prod-immutable-monitor.adoc
- templates/docs/rhpam70-prod.adoc
- templates/docs/rhpam70-sit.adoc
- templates/rhpam70-prod-immutable-monitor.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
Addresses https://issues.jboss.org/browse/RHPAM-1119
Removes the possibility to configure the listening port for the smart router whereas it is still possible to configure it in the other templates where the kie server needs to connect to an external smart router instance
> [RHPAM-1119] set router listening port static

- templates/rhpam70-authoring-ha.yaml
- templates/rhpam70-authoring.yaml
- templates/rhpam70-kieserver-mysql.yaml
- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
- templates/rhpam70-trial-ephemeral.yaml
[RHPAM-1166] Correct maven credentials parameter as optional and consistent description to indicate as such
> [RHPAM-1166] Correct maven credentials parameter as optional

- templates/rhpam70-authoring-ha.yaml
- templates/rhpam70-kieserver-externaldb.yaml
- templates/rhpam70-kieserver-mysql.yaml
- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1140 by removing the TX_ISOLATION env variable as it is defined in the scripts with a default value
https://github.com/jboss-container-images/jboss-kie-modules/blob/7.0.x/os.bpmsuite.executionserver/added/launch/bpmsuite-executionserver.sh#L111
> [RHPAM-1140] remove tx_isolation var

- templates/contrib/jdbc/README.md
- templates/contrib/jdbc/build.sh
- templates/contrib/jdbc/db2-driver-image/Dockerfile
- templates/contrib/jdbc/db2-driver-image/install.properties
- templates/contrib/jdbc/db2-driver-image/modules/system/layers/openshift/com/ibm/main/module.xml
- templates/contrib/jdbc/derby-driver-image/Dockerfile
- templates/contrib/jdbc/derby-driver-image/install.properties
- templates/contrib/jdbc/derby-driver-image/modules/system/layers/openshift/org/apache/derby/main/module.xml
- templates/contrib/jdbc/install.sh
- templates/contrib/jdbc/mariadb-driver-image/Dockerfile
- templates/contrib/jdbc/mariadb-driver-image/install.properties
- templates/contrib/jdbc/mariadb-driver-image/modules/system/layers/openshift/org/mariadb/main/module.xml
- templates/contrib/jdbc/mssql-driver-image/Dockerfile
- templates/contrib/jdbc/mssql-driver-image/install.properties
- templates/contrib/jdbc/mssql-driver-image/modules/system/layers/openshift/com/microsoft/main/module.xml
- templates/contrib/jdbc/oracle-driver-image/Dockerfile
- templates/contrib/jdbc/oracle-driver-image/install.properties
- templates/contrib/jdbc/oracle-driver-image/modules/system/layers/openshift/com/oracle/main/module.xml
- templates/contrib/jdbc/sybase-driver-image/Dockerfile
- templates/contrib/jdbc/sybase-driver-image/install.properties
- templates/contrib/jdbc/sybase-driver-image/modules/system/layers/openshift/com/sybase/main/module.xml
- templates/rhpam70-authoring-ha.yaml
- templates/rhpam70-authoring.yaml
- templates/rhpam70-kieserver-externaldb.yaml
- templates/rhpam70-kieserver-mysql.yaml
- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
- templates/rhpam70-trial-ephemeral.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1092
* Added support script to help building JDBC Driver images and the extended KIE Server image easily.
* Templates have been adapted to allow specifying the KIE Server image name in case a generated image is preferred.
> [RHPAM-1092] Provide support and tools for additional JDBC drivers in RHPAM/OCP

- templates/rhpam70-kieserver-externaldb.yaml
- templates/rhpam70-kieserver-mysql.yaml
- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
[RHPAM-1217] Remove EAP ADMIN parameters from kieserver templates
https://issues.jboss.org/browse/RHPAM-1217
> [RHPAM-1217] Remove EAP ADMIN parameters from kieserver templates in RHPAM

- templates/rhpam70-kieserver-externaldb.yaml
- templates/rhpam70-kieserver-mysql.yaml
- templates/rhpam70-kieserver-postgresql.yaml
- templates/rhpam70-prod-immutable-kieserver.yaml
- templates/rhpam70-prod-immutable-monitor.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
[RHPAM-1236] Missing MAVEN_REPO_SERVICE parameter in kieserver templates in RHPAM
https://issues.jboss.org/browse/RHPAM-1236
> [RHPAM-1236] Missing MAVEN_REPO_SERVICE parameter in kieserver templates in RHPAM

- templates/rhpam70-kieserver-externaldb.yaml
[RHPAM-1092] add DriverType ejb timer xa connection property for db2
https://issues.jboss.org/browse/RHPAM-1092
> [RHPAM-1092] add DriverType ejb timer xa connection property for db2

- templates/rhpam71-authoring.yaml
- templates/rhpam71-prod-immutable-monitor.yaml
- templates/rhpam71-prod.yaml
- templates/rhpam71-sit.yaml
- templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1485] PROBE_* env vars should not exist in templates anymore
https://issues.jboss.org/browse/RHPAM-1485
> [RHPAM-1485] PROBE_* env vars should not exist in templates anymore

- templates/rhpam71-authoring-ha.yaml
- templates/rhpam71-authoring.yaml
- templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1491] GIT_HOOKS_DIR parameter not exposed in RHPAM templates
https://issues.jboss.org/browse/RHPAM-1491
> [RHPAM-1491] GIT_HOOKS_DIR parameter not exposed in RHPAM templates

- templates/rhpam70-authoring-ha.yaml
- templates/rhpam70-authoring.yaml
- templates/rhpam70-prod-immutable-monitor.yaml
- templates/rhpam70-prod.yaml
- templates/rhpam70-sit.yaml
- templates/rhpam70-trial-ephemeral.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1361
Depends on https://github.com/jboss-openshift/cct_module/pull/270
> [RHPAM-1361] Add SSO principal-attribute

- templates/rhpam71-authoring-ha.yaml
- templates/rhpam71-kieserver-mysql.yaml
- templates/rhpam71-kieserver-postgresql.yaml
- templates/rhpam71-prod-immutable-kieserver.yaml
- templates/rhpam71-prod.yaml
- templates/rhpam71-sit.yaml
[RHPAM-1171] Missing image streams for databases in "rhpam70-image-streams.yaml"
https://issues.jboss.org/browse/RHPAM-1171
> [RHPAM-1171] Missing image streams for databases in "rhpam70-image-streams.yaml"

- templates/rhpam71-authoring-ha.yaml
- templates/rhpam71-authoring.yaml
- templates/rhpam71-kieserver-externaldb.yaml
- templates/rhpam71-kieserver-mysql.yaml
- templates/rhpam71-kieserver-postgresql.yaml
- templates/rhpam71-prod-immutable-kieserver.yaml
- templates/rhpam71-prod-immutable-monitor.yaml
- templates/rhpam71-prod.yaml
- templates/rhpam71-sit.yaml
- templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1452] Maven repository id should be configurable instead of generated
https://issues.jboss.org/browse/RHPAM-1452
> [RHPAM-1452] RHPAM Maven repository id should be configurable instead of generated

- templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1395] change KIE_ADMIN_PWD and KIE_SERVER_PWD to DEFAULT_PASSWORD
https://issues.jboss.org/browse/RHPAM-1395
> [RHPAM-1395] change KIE_ADMIN_PWD and KIE_SERVER_PWD to DEFAULT_PASSWORD

- smartrouter/image.yaml
[KIECLOUD-35] Smart router OpenShift image fails to start
https://issues.jboss.org/browse/KIECLOUD-35
> [KIECLOUD-35] Smart router OpenShift image fails to start

- businesscentral-monitoring/dev-overrides.yaml
- businesscentral/dev-overrides.yaml
- controller/dev-overrides.yaml
- kieserver/dev-overrides.yaml
[KIECLOUD-20] updated jboss-eap-modules from EAP72-CR5 branch to EAP72-CR5-1 tag
> [KIECLOUD-20] updated jboss-eap-modules from EAP72-CR5 branch to EAP72-CR5-1 tag

- businesscentral-monitoring/dev-overrides.yaml
- businesscentral-monitoring/rel-overrides.yaml
- businesscentral/dev-overrides.yaml
- businesscentral/rel-overrides.yaml
- controller/dev-overrides.yaml
- controller/rel-overrides.yaml
- kieserver/dev-overrides.yaml
- kieserver/rel-overrides.yaml
[KIECLOUD-20] final move to EAP_720 tags, which are identical to EAP72_CR5 tag in jboss-eap-7-image and EAP72_CR5-1 tag in jboss-eap-modules
> [KIECLOUD-20] final move to EAP_720 tags

- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- controller/image.yaml
- kieserver/image.yaml
- templates/rhpam73-trial-ephemeral.yaml
[KIECLOUD-107] Add Prometheus module to EAP-based RHPAM 7 images
https://issues.jboss.org/browse/KIECLOUD-107
> [KIECLOUD-107] Add Prometheus config to EAP-based RHPAM 7 images

- templates/rhpam73-authoring-ha.yaml
JIRA Link: https://issues.jboss.org/browse/KIECLOUD-114
After some discussion, instead of adding app labels in all templates, we decided to remove the app labels as they are automatically generated by OpenShift. Although I still believe we must change the application
label to another thing as app and application labels semantically mean the same.
Signed-off-by: rimolive <ricardo.martinelli.oliveira@gmail.com>
> [KIECLOUD-114] Remove app label from authoring HA template

- templates/rhpam73-authoring-ha.yaml
JIRA Link: https://issues.jboss.org/browse/RHDM-870
"ping" must be used as Service name as AMQ clustering configuration hard-coded this name.
> [RHDM-870] Fix AMQ ping service name

- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- templates/rhpam73-authoring-ha.yaml
- templates/rhpam73-authoring.yaml
- templates/rhpam73-managed.yaml
- templates/rhpam73-prod-immutable-monitor.yaml
- templates/rhpam73-trial-ephemeral.yaml
Adding a runtime configuration parameter in terms of system property and environment variable for enabling BC/WB KIE server global discovery.
Related JIRA
https://issues.jboss.org/browse/KIECLOUD-134
https://issues.jboss.org/projects/JBPM/issues/JBPM-8269
> [KIECLOUD-134] (7.3.0) Enhance KieServerStateOpenShiftRepository - Fixing naming issue

- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- templates/rhpam74-authoring-ha.yaml
- templates/rhpam74-authoring.yaml
- templates/rhpam74-managed.yaml
- templates/rhpam74-prod-immutable-monitor.yaml
- templates/rhpam74-trial-ephemeral.yaml
Adding a runtime configuration parameter in terms of system property and environment variable for enabling BC/WB KIE server global discovery.
Related JIRA
- https://issues.jboss.org/browse/KIECLOUD-134
- https://issues.jboss.org/projects/JBPM/issues/JBPM-8269
> [KIECLOUD-134] Enhance KieServerStateOpenShiftRepository

- templates/rhpam73-authoring-ha.yaml
[KIECLOUD-148] System property org.uberfire.nio.git.ssh.hostname not provided
https://issues.jboss.org/browse/KIECLOUD-148
> [KIECLOUD-148] (7.3.x) System property org.uberfire.nio.git.ssh.hostname not provided

- templates/rhpam74-authoring-ha.yaml
[KIECLOUD-148] System property org.uberfire.nio.git.ssh.hostname not provided
https://issues.jboss.org/browse/KIECLOUD-148
> [KIECLOUD-148] (master) System property org.uberfire.nio.git.ssh.hostname not provided

- templates/rhpam73-trial-ephemeral.yaml
[KIECLOUD-159] Remove prometheus template params from trial-ephemeral templates in 7.3.0
https://issues.jboss.org/browse/KIECLOUD-159 
> [KIECLOUD-159] Remove prometheus template params from trial-ephemeral templates in 7.3.0

- templates/rhpam74-authoring.yaml
- templates/rhpam74-kieserver-externaldb.yaml
- templates/rhpam74-kieserver-mysql.yaml
- templates/rhpam74-kieserver-postgresql.yaml
- templates/rhpam74-managed.yaml
- templates/rhpam74-prod-immutable-kieserver-amq.yaml
- templates/rhpam74-prod-immutable-kieserver.yaml
- templates/rhpam74-trial-ephemeral.yaml
To resolve an intermittent issue may occur during the KIE server DC rollout due to sticky session and eager Pod termination.
Related JIRA
https://issues.jboss.org/projects/RHPAM/issues/RHPAM-1952
> [RHPAM-1952] (7.4.0 - Ready) Exception is thrown by Business central when user clicks on deployment unit

- templates/rhpam73-authoring.yaml
- templates/rhpam73-kieserver-externaldb.yaml
- templates/rhpam73-kieserver-mysql.yaml
- templates/rhpam73-kieserver-postgresql.yaml
- templates/rhpam73-managed.yaml
- templates/rhpam73-prod-immutable-kieserver.yaml
- templates/rhpam73-trial-ephemeral.yaml
To resolve an intermittent issue may occur during the KIE server DC rollout due to sticky session and eager Pod termination.
Related JIRA
https://issues.jboss.org/projects/RHPAM/issues/RHPAM-1952
> [RHPAM-1952] (7.3.1 - Ready) Exception is thrown by Business central when user clicks on deployment unit

- templates/rhpam73-authoring-ha.yaml
- templates/rhpam73-authoring.yaml
- templates/rhpam73-kieserver-externaldb.yaml
- templates/rhpam73-kieserver-mysql.yaml
- templates/rhpam73-kieserver-postgresql.yaml
- templates/rhpam73-managed.yaml
- templates/rhpam73-prod-immutable-kieserver.yaml
- templates/rhpam73-prod-immutable-monitor.yaml
- templates/rhpam73-prod.yaml
- templates/rhpam73-trial-ephemeral.yaml
[RHPAM] (7.3.x) Setting Maven Mirror URL does not exclude Business Central
https://issues.jboss.org/browse/RHPAM-1994
> [RHPAM-1994] Setting Maven Mirror URL does not exclude Business Central

- quickstarts/library-process/README.md
- quickstarts/library-process/library-client/pom.xml
- quickstarts/library-process/library-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/client/LibraryClient.java
- quickstarts/library-process/library-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/client/LibraryServlet.java
- quickstarts/library-process/library-client/src/test/java/org/openshift/quickstarts/rhpam/kieserver/library/client/LibraryTest.java
- quickstarts/library-process/library/pom.xml
- quickstarts/library-process/library/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/Library.java
- quickstarts/library-process/library/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/LibraryTransaction.java
- quickstarts/library-process/library/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/types/Book.java
- quickstarts/library-process/library/src/main/resources/META-INF/persistence.xml
- quickstarts/library-process/library/src/test/java/org/openshift/quickstarts/rhpam/kieserver/library/LibraryTest.java
- quickstarts/library-process/library/src/test/resources/META-INF/persistence.xml
- quickstarts/library-process/pom.xml
- templates/rhpam74-kieserver-externaldb.yaml
- templates/rhpam74-kieserver-mysql.yaml
- templates/rhpam74-kieserver-postgresql.yaml
- templates/rhpam74-prod-immutable-kieserver-amq.yaml
- templates/rhpam74-prod-immutable-kieserver.yaml
See:
https://issues.jboss.org/browse/KIECLOUD-181
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> [KIECLOUD-181]  Refactoring RHPAM quickstarter for JDK 11 compatibility

- businesscentral-monitoring/branch-overrides.yaml
- businesscentral/branch-overrides.yaml
- controller/branch-overrides.yaml
- kieserver/branch-overrides.yaml
[RHPAM-2016] Update RHPAM images to use RHEL8 (UBI) base layer
https://issues.jboss.org/browse/RHPAM-2016
> [RHPAM-2016] Update RHPAM images to use RHEL8 (UBI) base layer

- templates/rhpam74-authoring.yaml
see:
https://issues.jboss.org/browse/RHPAM-2125
Have to create a entire new set of `EJB_TIMER` properties to configure the DS properly. The `AUTO_CONFIGURE_EJB_TIMER` is not working as intended (using the same URL from RHPAM). I should take a look into it tomorrow and could update this PR, removing the EJB_TIMER variables set.
@errantepiphany could you review, please? I should probably open a new JIRA for the AUTO_CONFIGURE_EJB_TIMER issue. If we have the time to look into it in this sprint, both JIRAs will be updated, otherwise I think this should do for the H2 database problem.
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> [RHPAM-2125] - Adding support for H2 Mixed Mode connection

- templates/docs/rhpam74-authoring.adoc
- templates/rhpam74-authoring.yaml
See: https://issues.jboss.org/browse/KIECLOUD-226
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> [KIECLOUD-226] - Set RHPAM_NONXA to false on authoring templates

- templates/rhpam75-prod.yaml
DROOLS_SERVER_FILTER_CLASSES and PROMETHEUS_SERVER_EXT_DISABLED moved to
be in same format as are variables for first Kie Server Deployment
Config
> [RHPAM-2254]Add Missing env variables to prod OpenShift template

- templates/rhpam74-prod.yaml
DROOLS_SERVER_FILTER_CLASSES and PROMETHEUS_SERVER_EXT_DISABLED moved to
be in same format as are variables for first Kie Server Deployment
Config
> [7.4.x][RHPAM-2254]Add Missing env variables to prod OpenShift template

- quickstarts/library-process/README.md
- quickstarts/library-process/library-client/pom.xml
- quickstarts/library-process/library-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/library/client/LibraryClient.java
- templates/rhpam75-prod-immutable-kieserver-amq.yaml
Follow up changes.
No service account is needed.
Need to expose the tcp-ssl port, 61617.
Configure the library-client to execut requests against a remote AMQ instance.
[KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
Follow up changes
> [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.

- templates/rhpam75-authoring-ha.yaml
[RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
https://issues.jboss.org/browse/RHPAM-2354
> [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing

- process-migration/README.adoc
- process-migration/branch-overrides.yaml
- process-migration/container.yaml
- process-migration/content_sets.yml
- process-migration/image.yaml
- process-migration/tag-overrides.yaml
Fix https://issues.jboss.org/browse/RHPAM-2311
Adds rhpam-7-openshift-image cekit module for building process-migration images
Depends on 
* https://github.com/jboss-container-images/jboss-kie-modules/pull/302
* https://github.com/jboss-container-images/rhpam-7-image/pull/156
> [RHPAM-2311] Add openshift module for proces-migration

- templates/contrib/jdbc/image.yaml
- templates/contrib/jdbc/modules/kie-custom-jdbc-driver/base-module.yaml
- templates/rhpam76-kieserver-externaldb.yaml
[KIECLOUD-332] image naming convention changes
https://issues.jboss.org/browse/KIECLOUD-332
> [KIECLOUD-332] image naming convention changes

- kieserver/image.yaml
[RHDM-1096] - Add missing environment variable for optaplanner thread pool queue size
See: https://issues.jboss.org/browse/RHDM-1096
> [RHDM-1096] - Add missing environment variable for optaplanner thread pool queue size

- templates/rhpam77-authoring-ha.yaml
[RHPAM-2608] Increase DataGrid 7.3 image tag version to 1.4 in OpenShift templates
https://issues.redhat.com/browse/RHPAM-2608
> [RHPAM-2608] Increase DataGrid 7.3 image tag version to 1.4 in OpenShift templates

- templates/rhpam77-authoring-ha.yaml
- templates/rhpam77-authoring.yaml
- templates/rhpam77-managed.yaml
- templates/rhpam77-prod-immutable-monitor.yaml
- templates/rhpam77-trial-ephemeral.yaml
Related JIRA link:
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2634
Related PRs
https://github.com/jboss-container-images/jboss-kie-modules/pull/346
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/411
https://github.com/kiegroup/kie-cloud-operator/pull/343
> [RHPAM-2634] Remote Server is lot from the controller after Kie Server scale down and scale up

- templates/rhpam77-authoring-ha.yaml
- templates/rhpam77-authoring.yaml
[RHPAM-2732] Kie Server is not connected to BC in Authoring template
https://issues.redhat.com/browse/RHPAM-2732
> [RHPAM-2732] Kie Server is not connected to BC in Authoring template

- templates/contrib/jdbc/Makefile
- templates/contrib/jdbc/README.md
Signed-off-by: ruromero <rromerom@redhat.com>
Fix https://issues.redhat.com/browse/RHPAM-2863
Default to `podman` build engine
Allow users to set a different one i.e. `docker`
Fix all the README.md warnings from markdownlint.
> [RHPAM-2863] Allow multiple build engines

- smartrouter/image.yaml
@spolti 7.9.x cherry pick of https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/477
> [RHPAM-3273] 7.9.x Fix example for LOG_LEVEL in SmartRouter image

- businesscentral-monitoring/branch-overrides.yaml
- businesscentral-monitoring/tag-overrides.yaml
- businesscentral/branch-overrides.yaml
- businesscentral/tag-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- dashbuilder/branch-overrides.yaml
- dashbuilder/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- smartrouter/branch-overrides.yaml
- smartrouter/tag-overrides.yaml
This version fixes issues when fetching activemq-rar-5.11.0.redhat-630495.rar
> [7.13.x] update jboss-eap-modules ref to latest EAP 7.4.6 tag

- businesscentral-monitoring/branch-overrides.yaml
- businesscentral-monitoring/tag-overrides.yaml
- businesscentral/branch-overrides.yaml
- businesscentral/tag-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- dashbuilder/branch-overrides.yaml
- dashbuilder/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- smartrouter/branch-overrides.yaml
- smartrouter/tag-overrides.yaml
This new version fixes issues when fetching activemq-rar-5.11.0.redhat-630495.rar
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/643
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/644
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/645
> [7.13.x-blue] update jboss-eap-modules ref to latest EAP 7.4.6 tag

- businesscentral-monitoring/branch-overrides.yaml
- businesscentral-monitoring/tag-overrides.yaml
- businesscentral/branch-overrides.yaml
- businesscentral/tag-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- dashbuilder/branch-overrides.yaml
- dashbuilder/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- smartrouter/branch-overrides.yaml
- smartrouter/tag-overrides.yaml
This new version fixes issues when fetching activemq-rar-5.11.0.redhat-630495.rar
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/643
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/644
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/645
> update jboss-eap-modules ref to latest EAP 7.4.6 tag

- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- controller/image.yaml
- dashbuilder/image.yaml
- kieserver/image.yaml
- process-migration/image.yaml
- smartrouter/image.yaml
This is required for now as latest ubi8 tag is using a RHEL 8.7 which seems to contain a bug and it is pulling an old version of nss package which is affected by a critical CVE.
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/650
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/651
> [7.13.x-blue] use 8.6 tag of ubi8 image for building the images

- businesscentral-monitoring/image.yaml
- businesscentral/image.yaml
- controller/image.yaml
- dashbuilder/image.yaml
- kieserver/image.yaml
- process-migration/image.yaml
- smartrouter/image.yaml
This is required for now as latest ubi8 tag is using a RHEL 8.7 which seems to contain a bug and it is pulling an old version of nss package which is affected by a critical CVE.
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/650
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/651
> [7.13.x] use 8.6 tag of ubi8 image for building the images
