jboss-container-images/rhpam-7-openshift-image

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[RHBA-512] RHBA image yamls needs corrected OSBS repository name and branch plus component label
https://issues.jboss.org/browse/RHBA-512
- [ x] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [x ] Pull Request contains link to the JIRA issue
- [x ] Pull Request contains description of the issue
- [x ] Pull Request does not include fixes for issues other than the main ticket
- [x ] Attached commits represent units of work and are properly formatted
- [x ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [x ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - …
=> [RHBA-512] RHBA image yamls needs corrected OSBS repository name and branch plus component label

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[RHBA-527] Rename RHBA OSBS repository branches
https://issues.jboss.org/browse/RHBA-527
=> [RHBA-527] Rename RHBA OSBS repository branches

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, kieserver/image.yaml
=> [RHBA-528] - Update activemq-rar version on RHBA images

templates/rhba70-businesscentral-monitoring-with-smartrouter.yaml, templates/rhba70-businesscentral-monitoring.yaml, templates/rhba70-businesscentral.yaml, templates/rhba70-full-mysql-persistent.yaml, templates/rhba70-full-mysql.yaml, templates/rhba70-kieserver-basic-s2i.yaml, templates/rhba70-kieserver-externaldb.yaml, templates/rhba70-kieserver-https-s2i.yaml, templates/rhba70-kieserver-postgresql.yaml, templates/rhba70-kieserver.yaml
=> [RHBA-613] - Increase Resource Memory limit in RHBA OpenShift templates

smartrouter/image.yaml
Fixes https://issues.jboss.org/browse/RHBA-530
Affects on https://github.com/jboss-container-images/jboss-kie-modules/pull/10
=> [RHBA-530] Add os-logging module and LAUNCH_DIR env var

elasticsearch/image.yaml, rhba70-image-streams.yaml, templates/elasticsearch.yaml
=> [RHBA-404] - Produce elasticsearch image for HA on RHDM and RHBA

elasticsearch/image.yaml
https://issues.jboss.org/browse/RHBA-404
[RHBA-404] Produce elasticsearch image for HA on RHBA
=> [RHBA-404] Produce elasticsearch image for HA on RHBA

elasticsearch/image.yaml
Produce elasticsearch image for HA on RHBA
https://issues.jboss.org/browse/RHBA-404
=> [RHBA-404] image name fix

rhba70-image-streams.yaml
=> [RHBA-404] Corrected the image name for elasticsearch

rhba70-image-streams.yaml
=> [RHBA-404] Corrected the image stream name for elasticsearch

templates/rhba70-businesscentral.yaml
[RHBA-639] Remove MySQL Image Stream Tag from Business Central OpenShift Template
https://issues.jboss.org/browse/RHBA-639
=> [RHBA-639] Remove MySQL Image Stream Tag from Business Central OpenShift Template

templates/rhpam70-authoring.yaml
https://issues.jboss.org/browse/RHPAM-730
=> [RHPAM-730] Switched from MySQL to persistent H2 in rhpam70-authoring template

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, kieserver/image.yaml
Fixes https://issues.jboss.org/browse/RHPAM-683
=> [RHPAM-683] Removed rh-maven33 dependency

elasticsearch/image.yaml
=> extend from elasticsearch:latest

templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml
Added rhpam70-kieserver-externaldb, rhpam70-kieserver-mysql, and rhpam70-kieserver-postgresql templates for KIE server setup examples
=> [RHPAM-724] Added 3 templates for KIE server setup

templates/rhpam70-authoring.yaml, templates/rhpam70-trial-ephemeral.yaml
Using multi-maven support to allow an external maven repo set up for both business central and KIE server, while business central is also acting as a maven service for KIE server
=> [RHPAM-724] In authoring environments, multiple maven repos are needed

templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-sit.yaml
Have Smart Router use persistent configuration to sync state across replicas
https://issues.jboss.org/browse/RHPAM-796
=> [RHPAM-796] Persistent smart router configuration to allow HA/restarts

templates/rhpam70-prod.yaml
https://issues.jboss.org/browse/RHPAM-724
=> [RHPAM-724] Adding rhpam70-prod template, for a managed HA production runtime environment

templates/rhpam70-authoring.yaml, templates/rhpam70-trial-ephemeral.yaml
Fixes https://issues.jboss.org/browse/RHPAM-780
Depends on:
* https://github.com/jboss-container-images/jboss-kie-modules/pull/27
* https://github.com/jboss-container-images/rhpam-7-image/pull/14
=> [RHPAM-780] Expose git-ssh port through service

templates/rhpam70-authoring.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
Addresses templates for https://issues.jboss.org/browse/RHDM-319
=> [RHDM-319] OpenShift - default Maven user should not be admin

kieserver/image.yaml
=> [RHPAM-181] - Kie server timers aren't clustered

templates/rhpam70-authoring.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
[https://issues.jboss.org/browse/RHPAM-874](https://issues.jboss.org/browse/RHPAM-874)
=> [RHPAM-874] Fix incorectly defined maven password

templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
Signed-off-by: calvin zhu <calvinzhu@hotmail.com>
=> [RHPAM-37] probe script fix for KIE server

templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
Ruben: Sort env vars and remove https from trial
Babak: Pass on smart router config to images
=> [RHPAM-802] Pass on router config to images, further cleanup

templates/rhpam70-authoring-ha.yaml
=> [RHPAM-1002] - OpenShift HA template for Business Central Authoring

businesscentral-indexing/image.yaml, rhpam70-image-streams.yaml, templates/rhpam70-authoring-ha.yaml
[RHPAM-1008] rename rhpam70-elasticsearch to rhpam70-businesscentral-indexing
https://issues.jboss.org/browse/RHPAM-1008
=> [RHPAM-1008] rename rhpam70-elasticsearch to rhpam70-businesscentral-indexing

templates/rhpam70-prod-immutable-kieserver.yaml
Signed-off-by: Jakub Schwan jschwan@redhat.com
=> [RHPAM-794] Fix typo in immutable Kie Server template

templates/rhpam70-authoring-ha.yaml
=> RHPAM-1002: Align HTTPS secrets with other templates

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
=> [RHPAM-769] - Session error after being idle for a few minutes

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
=> [RHPAM-802] - Review and clean up all templates

kieserver/image.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml
=> [RHPAM-794] - Allow KIE server / OpenShift to be completely immutable

templates/rhpam70-authoring-ha.yaml
template rhpam70-authoring-ha.yaml template does not contain description on kie server service ports.
=> [RHPAM-859] - Generate OpenShift application template docs

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
In order to enable the user to modify templates easily, marked out blocks using comments. The work seems complete except for the immutable monitoring template, which I won't do right now.
=> [BXMSDOC-2481] Marked blocks in templates

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1076
=> [RHPAM-1076] Set authentication to BC probes

templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml
https://issues.jboss.org/browse/RHPAM-1152
Rebased to the rhpam70-dev.
=> Remove duplicated required parameter from Kie server templates

templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
Solves https://issues.jboss.org/browse/RHPAM-1119
=> [RHPAM-1119] Allow router port to be configurable

templates/rhpam70-authoring-ha.yaml
=> [RHPAM-1141] - AMQ readiness check fails on rhpam70-authoring-ha

rhpam70-image-streams.yaml
[RHPAM-1163] Broken link to rhpam70-businesscentral-indexing-openshift in image stream file
https://issues.jboss.org/browse/RHPAM-1163
=> [RHPAM-1163] Broken link to rhpam70-businesscentral-indexing-openshift in image stream file

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1156
=> [RHPAM-1156] Aligned logmanager version

templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
Fixes replacement error in https://issues.jboss.org/browse/RHPAM-1119
=> [RHPAM-1119] Fix default value for router port

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-trial-ephemeral.yaml
[RHPAM-1166] Maven repo parameter issues in OpenShift templates
https://issues.jboss.org/browse/RHPAM-1166
=> [RHPAM-1166] Maven repo parameter issues in OpenShift templates

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, rhpam70-image-streams.yaml, smartrouter/image.yaml, templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
[RHPAM-1208] Update RHPAM OpenShift images from 7.0.0.GA to 7.0.1
https://issues.jboss.org/browse/RHPAM-1208
=> [RHPAM-1208] Update RHPAM OpenShift images from 7.0.0.GA to 7.0.1.CR1

templates/docs/rhpam70-authoring-ha.adoc, templates/docs/rhpam70-authoring.adoc, templates/docs/rhpam70-kieserver-externaldb.adoc, templates/docs/rhpam70-kieserver-mysql.adoc, templates/docs/rhpam70-kieserver-postgresql.adoc, templates/docs/rhpam70-prod-immutable-kieserver.adoc, templates/docs/rhpam70-prod-immutable-monitor.adoc, templates/docs/rhpam70-prod.adoc, templates/docs/rhpam70-sit.adoc, templates/docs/rhpam70-trial-ephemeral.adoc
=> [RHPAM-1208] - Update RHPAM OpenShift images from 7.0.0.GA to 7.0.1.CR1

templates/docs/rhpam70-authoring-ha.adoc, templates/docs/rhpam70-authoring.adoc, templates/docs/rhpam70-kieserver-mysql.adoc, templates/docs/rhpam70-kieserver-postgresql.adoc, templates/docs/rhpam70-prod-immutable-kieserver.adoc, templates/docs/rhpam70-prod.adoc, templates/docs/rhpam70-sit.adoc, templates/docs/rhpam70-trial-ephemeral.adoc
[RHPAM-1166] maven repo params docs update
https://issues.jboss.org/browse/RHPAM-1166
=> [RHPAM-1166] maven repo params docs update

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
add the SSO HOSTNAME_HTTP|S again, it was wrongly removed by previous commit.
=> [RHPAM-1309] - Allow set kie server location to external URL in RHPAM

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
Fixes https://issues.jboss.org/browse/RHPAM-1235
=> [RHPAM-1235] Database probes in the templates are missing

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
=> update jboss-kie-modules to master

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
=> [RHPAM-1349] - Remove xpaas label from RHPAM templates

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
=> version and rhpam label version should be between double quotes

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[RHPAM-1368] Update RHPAM OpenShift images from 7.0.1 to 7.0.2
https://issues.jboss.org/browse/RHPAM-1368
=> [RHPAM-1368] Update RHPAM OpenShift images from 7.0.1 to 7.0.2

templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml
=> [RHPAM-1252] - Kie server doesn't survive PostgreSQL restart

templates/docs/README.adoc, templates/docs/rhpam70-authoring-ha.adoc, templates/docs/rhpam70-authoring.adoc, templates/docs/rhpam70-kieserver-externaldb.adoc, templates/docs/rhpam70-kieserver-mysql.adoc, templates/docs/rhpam70-kieserver-postgresql.adoc, templates/docs/rhpam70-prod-immutable-kieserver.adoc, templates/docs/rhpam70-prod-immutable-monitor.adoc, templates/docs/rhpam70-prod.adoc, templates/docs/rhpam70-sit.adoc, templates/docs/rhpam70-trial-ephemeral.adoc
=> update template docs

.gitignore
=> [RHPAM-1435] make .gitignore ignore any "my" .yaml file

rhpam71-image-streams.yaml
=> update imagestreams to registry.redhat.io

templates/rhpam70-authoring-ha.yaml, templates/rhpam70-authoring.yaml, templates/rhpam70-kieserver-externaldb.yaml, templates/rhpam70-kieserver-mysql.yaml, templates/rhpam70-kieserver-postgresql.yaml, templates/rhpam70-prod-immutable-kieserver.yaml, templates/rhpam70-prod-immutable-monitor.yaml, templates/rhpam70-prod.yaml, templates/rhpam70-sit.yaml, templates/rhpam70-trial-ephemeral.yaml
=> [RHPAM-1395] - Improve the template message

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
=> [RHPAM-1395] - Improve the template message (#116)

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
=> [RHPAM-1478] - Standardize application templates

businesscentral-indexing/cp-overrides.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/cp-overrides.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/cp-overrides.yaml, businesscentral/rel-overrides.yaml, controller/cp-overrides.yaml, controller/rel-overrides.yaml, kieserver/cp-overrides.yaml, kieserver/rel-overrides.yaml, smartrouter/cp-overrides.yaml, smartrouter/rel-overrides.yaml
[RHPAM-1361] update to CE sprint-23 branch to get CLOUD-2722 changes needed by RHPAM-1361
https://issues.jboss.org/browse/RHPAM-1361
=> [RHPAM-1361] update to CE sprint-23 branch to get CLOUD-2722 changes needed by RHPAM-1361

businesscentral/image.yaml, templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1491] fix git hooks dir
https://issues.jboss.org/browse/RHPAM-1491
=> [RHPAM-1491] fix git hooks dir

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
Cherry-pick b0e99f43d9100623326fcc368a86386193c4d729 for 7.1 templates
Related to https://issues.jboss.org/browse/RHPAM-1361
=> [RHPAM-1361] Add SSO principal-attribute 7.1

businesscentral-indexing/image.yaml
[RHPAM-1481] Update RHPAM binaries in images from 7.0.2 to 7.1.0
https://issues.jboss.org/browse/RHPAM-1481
=> [RHPAM-1481] Update RHPAM binaries in images from 7.0.2 to 7.1.0

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1505] RH-SSO and LDAP absent in some RHPAM OpenShift templates
https://issues.jboss.org/browse/RHPAM-1505
=> [RHPAM-1505] RH-SSO and LDAP absent in RHPAM OpenShift immutable server templates

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
=> [RHPAM-1361] fix back to sprint-23 of CE and EAP

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1505] set controller protocol properly for kieserver and smartrouter
https://issues.jboss.org/browse/RHPAM-1505
=> [RHPAM-1505] set controller protocol properly for kieserver and smartrouter

templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml
=> [KIECLOUD-10] Remove unused template properties

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-prod-immutable-monitor.yaml
=> [KIECLOUD-10] - Unused properties in templates and missing labels

.gitignore
KIECLOUD-12: add my*.json to .gitignore in addition to my*.yaml in RHDM/RHPAM
https://issues.jboss.org/browse/KIECLOUD-12
=> KIECLOUD-12: add my*.json to .gitignore in addition to my*.yaml in RHDM/RHPAM

templates/rhpam71-trial-ephemeral.yaml
[RHPAM-1434] Provide CORS configuration support for Kie Server in RHPAM
https://issues.jboss.org/browse/RHPAM-1434
=> [RHPAM-1434] Provide CORS configuration support for Kie Server in RHPAM

.circleci/config.yml, templates/README.md
=> prepare for circleci integration

businesscentral-indexing/cp-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/cp-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/cp-overrides.yaml, businesscentral/image.yaml, businesscentral/rel-overrides.yaml, controller/cp-overrides.yaml, controller/image.yaml, controller/rel-overrides.yaml, kieserver/cp-overrides.yaml, kieserver/image.yaml, kieserver/rel-overrides.yaml, smartrouter/cp-overrides.yaml, smartrouter/image.yaml, smartrouter/rel-overrides.yaml
[RHPAM-1613] Update CE Sprint from 23 to 24 in RHPAM
https://issues.jboss.org/browse/RHPAM-1613
=> [RHPAM-1613] Update CE Sprint from 23 to 24 in RHPAM

templates/rhpam71-authoring-ha.yaml, templates/rhpam71-authoring.yaml, templates/rhpam71-kieserver-externaldb.yaml, templates/rhpam71-kieserver-mysql.yaml, templates/rhpam71-kieserver-postgresql.yaml, templates/rhpam71-prod-immutable-kieserver.yaml, templates/rhpam71-prod-immutable-monitor.yaml, templates/rhpam71-prod.yaml, templates/rhpam71-sit.yaml, templates/rhpam71-trial-ephemeral.yaml
Fix https://issues.jboss.org/browse/RHPAM-1515
=> [RHPAM-1515] Add RoleMapping properties to templates

rhpam72-image-streams.yaml
[RHPAM-1614] Update versions in images, streams, templates, & docs from 7.1 to 7.2 in RHPAM
https://issues.jboss.org/browse/RHPAM-1614
=> [RHPAM-1614] Update versions in images, streams, templates, & docs from 7.1 to 7.2 in RHPAM

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, ce.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[RHPAM-1625] Integrate RHPAM with new engineering CI system
https://issues.jboss.org/browse/RHPAM-1625
=> [RHPAM-1625] Integrate RHPAM with new engineering CI system

businesscentral-indexing/cp-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/cp-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/cp-overrides.yaml, businesscentral/image.yaml, businesscentral/rel-overrides.yaml, controller/cp-overrides.yaml, controller/image.yaml, controller/rel-overrides.yaml, kieserver/cp-overrides.yaml, kieserver/image.yaml, kieserver/rel-overrides.yaml, smartrouter/cp-overrides.yaml, smartrouter/image.yaml, smartrouter/rel-overrides.yaml
[RHPAM-1614] correct versions
https://issues.jboss.org/browse/RHPAM-1614
=> [RHPAM-1614] correct versions

templates/docs/rhpam72-authoring-ha.adoc, templates/rhpam72-authoring-ha.yaml
[KIECLOUD-29] Update RHDM and RHPAM AMQ broker from 7.1 to 7.2
https://issues.jboss.org/browse/KIECLOUD-29
=> [KIECLOUD-29] Update RHDM and RHPAM AMQ broker from 7.1 to 7.2

templates/rhpam72-authoring-ha.yaml, templates/rhpam72-authoring.yaml, templates/rhpam72-kieserver-externaldb.yaml, templates/rhpam72-kieserver-mysql.yaml, templates/rhpam72-kieserver-postgresql.yaml, templates/rhpam72-prod-immutable-kieserver.yaml, templates/rhpam72-prod.yaml, templates/rhpam72-trial-ephemeral.yaml
[KIECLOUD-20] revert to external route for org.kie.server.location
=> [KIECLOUD-20] revert to external route for org.kie.server.location

templates/rhpam72-kieserver-externaldb.yaml
[RHPAM-904] revert addition of kieserver extension image
https://issues.jboss.org/browse/RHPAM-904
=> [RHPAM-904] revert addition of kieserver extension image

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[KIECLOUD-33] fix repository references in RHPAM image.yaml files
https://issues.jboss.org/browse/KIECLOUD-33
=> [KIECLOUD-33] fix repository references in RHPAM image.yaml files

businesscentral-monitoring/dev-overrides.yaml, businesscentral/dev-overrides.yaml, controller/dev-overrides.yaml, kieserver/dev-overrides.yaml
[KIECLOUD-20] switch to EAP72-RC1
=> [KIECLOUD-20] switch to EAP72-RC1

businesscentral-indexing/cp-overrides.yaml, businesscentral-indexing/dev-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/cp-overrides.yaml, businesscentral-monitoring/dev-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/cp-overrides.yaml, businesscentral/dev-overrides.yaml, businesscentral/image.yaml, businesscentral/rel-overrides.yaml, controller/cp-overrides.yaml, controller/dev-overrides.yaml, controller/image.yaml, controller/rel-overrides.yaml, kieserver/cp-overrides.yaml, kieserver/dev-overrides.yaml, kieserver/image.yaml, kieserver/rel-overrides.yaml, smartrouter/cp-overrides.yaml, smartrouter/dev-overrides.yaml, smartrouter/image.yaml, smartrouter/rel-overrides.yaml
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>
=> BXMSPROD-207 resign from -dev and -cp branches in dist-git.

templates/docs/README.adoc, templates/docs/rhpam72-authoring-ha.adoc, templates/docs/rhpam72-authoring.adoc, templates/docs/rhpam72-kieserver-externaldb.adoc, templates/docs/rhpam72-kieserver-mysql.adoc, templates/docs/rhpam72-kieserver-postgresql.adoc, templates/docs/rhpam72-prod-immutable-kieserver.adoc, templates/docs/rhpam72-prod-immutable-monitor.adoc, templates/docs/rhpam72-prod.adoc, templates/docs/rhpam72-trial-ephemeral.adoc
=> [KIECLOUD-39] - Generete the template docs for branch 7.2.x

businesscentral-indexing/container.yaml, businesscentral-indexing/content_sets.yml, businesscentral-indexing/dev-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/container.yaml, businesscentral-monitoring/content_sets.yml, businesscentral-monitoring/dev-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/container.yaml, businesscentral/content_sets.yml, businesscentral/dev-overrides.yaml, businesscentral/image.yaml, businesscentral/rel-overrides.yaml, controller/container.yaml, controller/content_sets.yml, controller/dev-overrides.yaml, controller/image.yaml, controller/rel-overrides.yaml, kieserver/container.yaml, kieserver/content_sets.yml, kieserver/dev-overrides.yaml, kieserver/image.yaml, kieserver/rel-overrides.yaml, smartrouter/container.yaml, smartrouter/content_sets.yml, smartrouter/dev-overrides.yaml, smartrouter/image.yaml, smartrouter/rel-overrides.yaml
[KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (master)
https://issues.jboss.org/browse/KIECLOUD-50
=> [KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (master)

businesscentral-indexing/container.yaml, businesscentral-indexing/content_sets.yml, businesscentral-indexing/dev-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/rel-overrides.yaml, businesscentral-monitoring/container.yaml, businesscentral-monitoring/content_sets.yml, businesscentral-monitoring/dev-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/rel-overrides.yaml, businesscentral/container.yaml, businesscentral/content_sets.yml, businesscentral/dev-overrides.yaml, businesscentral/image.yaml, businesscentral/rel-overrides.yaml, controller/container.yaml, controller/content_sets.yml, controller/dev-overrides.yaml, controller/image.yaml, controller/rel-overrides.yaml, kieserver/container.yaml, kieserver/content_sets.yml, kieserver/dev-overrides.yaml, kieserver/image.yaml, kieserver/rel-overrides.yaml, smartrouter/container.yaml, smartrouter/content_sets.yml, smartrouter/dev-overrides.yaml, smartrouter/image.yaml, smartrouter/rel-overrides.yaml
[KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (7.2.x)
https://issues.jboss.org/browse/KIECLOUD-50
=> [KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (7.2.x)

businesscentral-indexing/container.yaml, businesscentral-indexing/content_sets.yml, businesscentral-monitoring/container.yaml, businesscentral-monitoring/content_sets.yml, businesscentral/container.yaml, businesscentral/content_sets.yml, controller/container.yaml, controller/content_sets.yml, kieserver/container.yaml, kieserver/content_sets.yml, smartrouter/container.yaml, smartrouter/content_sets.yml
[KIECLOUD-66] ppc64le should not be included in container.yaml and content_sets.yml files
https://issues.jboss.org/browse/KIECLOUD-66
=> [KIECLOUD-66] ppc64le should not be included in container.yaml and content_sets.yml files

businesscentral-monitoring/dev-overrides.yaml, businesscentral/dev-overrides.yaml, controller/dev-overrides.yaml, kieserver/dev-overrides.yaml, templates/rhpam72-authoring-ha.yaml
[KIECLOUD-70] Update images to align with EAP72-CR2-1
https://issues.jboss.org/browse/KIECLOUD-70
=> [KIECLOUD-70] Update images to align with EAP72-CR2-1

templates/rhpam72-authoring-ha.yaml, templates/rhpam72-authoring.yaml, templates/rhpam72-kieserver-externaldb.yaml, templates/rhpam72-kieserver-mysql.yaml, templates/rhpam72-kieserver-postgresql.yaml, templates/rhpam72-prod-immutable-kieserver.yaml, templates/rhpam72-prod-immutable-monitor.yaml, templates/rhpam72-prod.yaml, templates/rhpam72-trial-ephemeral.yaml
=> [BXMSDOC-3456] - RHPAM template review by tech writer (7.2.x)

templates/rhpam72-authoring-ha.yaml, templates/rhpam72-authoring.yaml, templates/rhpam72-kieserver-externaldb.yaml, templates/rhpam72-kieserver-mysql.yaml, templates/rhpam72-kieserver-postgresql.yaml, templates/rhpam72-prod-immutable-kieserver.yaml, templates/rhpam72-prod-immutable-monitor.yaml, templates/rhpam72-prod.yaml, templates/rhpam72-trial-ephemeral.yaml
=> [BXMSDOC-3456] - RHPAM template review by tech writer (master)

templates/docs/README.adoc, templates/docs/rhpam72-authoring-ha.adoc, templates/docs/rhpam72-authoring.adoc, templates/docs/rhpam72-kieserver-externaldb.adoc, templates/docs/rhpam72-kieserver-mysql.adoc, templates/docs/rhpam72-kieserver-postgresql.adoc, templates/docs/rhpam72-prod-immutable-kieserver.adoc, templates/docs/rhpam72-prod-immutable-monitor.adoc, templates/docs/rhpam72-prod.adoc, templates/docs/rhpam72-trial-ephemeral.adoc
=> [BXMSDOC-3456] - Edit all OpenShift templates for RHPAM and RHDM 7.2

businesscentral-monitoring/dev-overrides.yaml, businesscentral/dev-overrides.yaml, controller/dev-overrides.yaml, kieserver/dev-overrides.yaml
[KIECLOUD-20] update EAP 7.2 to CR3
=> [KIECLOUD-20] update EAP 7.2 to CR3

businesscentral-monitoring/dev-overrides.yaml, businesscentral/dev-overrides.yaml, controller/dev-overrides.yaml, kieserver/dev-overrides.yaml
[KIECLOUD-20] update EAP 7.2 to CR4
=> [KIECLOUD-20] update EAP 7.2 to CR4

rhpam73-image-streams.yaml
=> [KIECLOUD-82] - Update ImageStreams Kind

businesscentral-monitoring/dev-overrides.yaml, businesscentral/dev-overrides.yaml, controller/dev-overrides.yaml, kieserver/dev-overrides.yaml
[KIECLOUD-20] Upgrade EAP to 7.2 CR5
=> [KIECLOUD-20] Upgrade EAP to 7.2 CR5

templates/rhpam73-kieserver-externaldb.yaml
=> [RHPAM-1179] - Support the use of database connection URL for EJB timers

templates/rhpam73-authoring-ha.yaml
Related JIRA: https://issues.jboss.org/browse/RHPAM-1180
* Added Additional Role and RoleBinding objects
* Added scaledown-controller for scale down events
* Required to add view role to default service account
(oc policy add-role-to-user view -z default)
Signed-off-by: rimolive <ricardo.martinelli.oliveira@gmail.com>
=> [RHPAM-1180] Change AMQ deployment to HA

templates/docs/README.adoc, templates/docs/rhpam72-prod-immutable-monitor.adoc, templates/docs/rhpam72-prod.adoc
=> [KIECLOUD-112] - Task regenerate the template docs

businesscentral-indexing/content_sets.yml, smartrouter/content_sets.yml
[RHPAM-1832] Several images fail content set testing
https://issues.jboss.org/browse/RHPAM-1832
=> [RHPAM-1832] Several images fail content set testing

templates/rhpam73-authoring-ha.yaml, templates/rhpam73-authoring.yaml
[KIECLOUD-123] expose MAVEN_MIRROR_URL parameter in authoring templates
https://issues.jboss.org/browse/KIECLOUD-123
=> [KIECLOUD-123] expose MAVEN_MIRROR_URL parameter in authoring templates

templates/rhpam73-authoring-ha.yaml, templates/rhpam73-kieserver-mysql.yaml, templates/rhpam73-kieserver-postgresql.yaml, templates/rhpam73-managed.yaml, templates/rhpam73-prod-immutable-kieserver.yaml, templates/rhpam73-prod.yaml
[RHPAM-1942] follow-up PR: remove unnecessary timer env vars
https://issues.jboss.org/browse/RHPAM-1942
=> [RHPAM-1942] follow-up PR: remove unnecessary timer env vars

templates/rhpam73-authoring-ha.yaml, templates/rhpam73-kieserver-mysql.yaml, templates/rhpam73-kieserver-postgresql.yaml, templates/rhpam73-managed.yaml, templates/rhpam73-prod-immutable-kieserver.yaml, templates/rhpam73-prod.yaml
[RHPAM-1970] Kie Server image not running correctly because EJB was initialized first
https://issues.jboss.org/browse/RHPAM-1970
=> [RHPAM-1970] (7.3.x) Kie Server image not running correctly because EJB was initialized first

templates/rhpam74-authoring-ha.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod.yaml
[RHPAM-1970] Kie Server image not running correctly because EJB was initialized first
https://issues.jboss.org/browse/RHPAM-1970
=> [RHPAM-1970] (master) Kie Server image not running correctly because EJB was initialized first

templates/rhpam74-authoring-ha-datagrid.yaml, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod-immutable-monitor.yaml, templates/rhpam74-prod.yaml, templates/rhpam74-trial-ephemeral.yaml
[RHPAM] (master) Setting Maven Mirror URL does not exclude Business Central
https://issues.jboss.org/browse/RHPAM-1994
=> [RHPAM-1994] Setting Maven Mirror URL does not exclude Business Central

businesscentral-indexing/image.yaml, businesscentral-indexing/tag-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, rhpam73-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/rhpam73-authoring-ha.yaml, templates/rhpam73-authoring.yaml, templates/rhpam73-kieserver-externaldb.yaml, templates/rhpam73-kieserver-mysql.yaml, templates/rhpam73-kieserver-postgresql.yaml, templates/rhpam73-managed.yaml, templates/rhpam73-prod-immutable-kieserver.yaml, templates/rhpam73-prod-immutable-monitor.yaml, templates/rhpam73-prod.yaml, templates/rhpam73-trial-ephemeral.yaml
[KIECLOUD-175] prepare 7.3.x branches for 7.3.1
https://issues.jboss.org/browse/KIECLOUD-175
=> [KIECLOUD-175] prepare 7.3.x branches for 7.3.1

templates/rhpam73-prod-immutable-kieserver.yaml
https://issues.jboss.org/browse/KIECLOUD-179
=> [KIECLOUD-179] [7.3.x] Fix KIE_SERVER_BYPASS_AUTH_USER display name

templates/rhpam74-prod-immutable-kieserver.yaml
https://issues.jboss.org/browse/KIECLOUD-179
=> [KIECLOUD-179] Fix KIE_SERVER_BYPASS_AUTH_USER display name

templates/rhpam74-prod-immutable-kieserver-amq.yaml
Updating the AMQ template accordingly
https://issues.jboss.org/browse/KIECLOUD-180
=> [KIECLOUD-180] Immutable Kieserver AMQ templates have incorrect naming

businesscentral-indexing/branch-overrides.yaml, businesscentral-indexing/tag-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/rhpam74-authoring-ha-datagrid.yaml, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod-immutable-monitor.yaml, templates/rhpam74-prod.yaml, templates/rhpam74-trial-ephemeral.yaml
[KIECLOUD-176] Update RHDM and RHPAM dependency references and versions
https://issues.jboss.org/browse/KIECLOUD-176
=> [KIECLOUD-176] Update RHDM and RHPAM dependency references and versions

templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-trial-ephemeral.yaml
This PR contains necessary changes in respond to a feature enhancement detailed at this following JIRA. 
Related JIRAs
- https://issues.jboss.org/projects/JBPM/issues/JBPM-8150
Related PRs
- https://github.com/kiegroup/droolsjbpm-integration/pull/1780
=> [JBPM-8150] Allow users to change Kie server id in Deployment config and templates

quickstarts/library-process/library/pom.xml, quickstarts/library-process/pom.xml
See:
https://issues.jboss.org/browse/KIECLOUD-186
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
=> [KIECLOUD-186] Maven repositories must made https calls instead http

businesscentral-indexing/branch-overrides.yaml, businesscentral-indexing/tag-overrides.yaml, businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[BAPL-1072] Cloud product build pipeline improvements
https://issues.jboss.org/browse/BAPL-1072
=> [BAPL-1072] Cloud product build pipeline improvements

templates/rhpam74-authoring-ha-datagrid.yaml, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod-immutable-monitor.yaml, templates/rhpam74-trial-ephemeral.yaml
Prepare RHPAM Templates to enable OpenShiftStartupStrategy as the default.
Related JIRA
https://issues.jboss.org/projects/KIECLOUD/issues/KIECLOUD-184
=> [KIECLOUD-184] (7.4.0) RHPAM OpenShiftStartupStrategy Full Release

templates/rhpam74-authoring-ha-datagrid.yaml, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod.yaml, templates/rhpam74-trial-ephemeral.yaml
[KIECLOUD-107] Add Prometheus config to EAP-based RHDM and RHPAM 7 images
https://issues.jboss.org/browse/KIECLOUD-1
=> [KIECLOUD-107] Add Prometheus config to EAP-based RHDM and RHPAM 7 images

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, kieserver/image.yaml, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
https://issues.jboss.org/browse/RHPAM-1387
=> [rhpam-1387] Allow set Smart router location to external URL in RHPAM

templates/rhpam74-authoring-ha-datagrid.yaml, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml
[KIECLOUD-221] upgrade datagrid and amq broker versions
https://issues.jboss.org/browse/KIECLOUD-221
=> [KIECLOUD-221] upgrade datagrid and amq broker versions

businesscentral-indexing/image.yaml, businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, smartrouter/image.yaml
[RHPAM-2016] fix osbs repo branch suffix per release guidelines
https://issues.jboss.org/browse/RHPAM-2016
=> [RHPAM-2016] fix osbs repo branch suffix per release guidelines

businesscentral-indexing/branch-overrides.yaml, businesscentral-indexing/image.yaml, businesscentral-indexing/tag-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
[RHPAM-2016] fix osbs repo branch suffix per clarified release guidelines
https://issues.jboss.org/browse/RHPAM-2016
=> [RHPAM-2016] fix osbs repo branch suffix per clarified release guidelines

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[KIECLOUD-236] align RHPAM 7.4.0 images with appropriate EAP 7.2.1 tags
https://issues.jboss.org/browse/KIECLOUD-236
=> [KIECLOUD-236] align RHPAM 7.4.0 images with appropriate EAP 7.2.1 tags

templates/docs/rhpam74-authoring-ha.adoc, templates/rhpam74-authoring-ha.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml
See: https://issues.jboss.org/browse/KIECLOUD-232
=> [KIECLOUD-232] - Update images of "amq-broker" to version 7.3

templates/rhpam74-authoring-ha.yaml, templates/rhpam74-authoring.yaml, templates/rhpam74-kieserver-externaldb.yaml, templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml, templates/rhpam74-managed.yaml, templates/rhpam74-prod-immutable-kieserver-amq.yaml, templates/rhpam74-prod-immutable-kieserver.yaml, templates/rhpam74-prod-immutable-monitor.yaml, templates/rhpam74-trial-ephemeral.yaml
a) Remove "KIE_SERVER_USE_SECURE_ROUTE_NAME"
b) Remove "secure-" prefix from templates and change to base name for https routes
c) Add "insecure-" prefix http routes
=> [KIECLOUD-97] Synchronize OpenShiftStartupStrategy related changes between Template, APB, and Operator

templates/rhpam74-kieserver-mysql.yaml, templates/rhpam74-kieserver-postgresql.yaml
https://issues.jboss.org/browse/RHPAM-2226
Validation subelement is missing for datasources
=> [RHPAM-2226] Validation subelement is missing for datasources

templates/rhpam75-kieserver-externaldb.yaml
https://issues.jboss.org/browse/KIECLOUD-271
Signed-off-by: tradisso <tradisso@tradisso.remote.csb>
=> KIECLOUD-271: corrected default parameter description for nonXA DS

templates/rhpam75-prod-immutable-monitor.yaml, templates/rhpam75-prod.yaml
See: https://issues.jboss.org/browse/RHPAM-1387
=> [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM

templates/contrib/jdbc/README.md, templates/contrib/jdbc/prepare.sh
=> [KIECLOUD-266] - Update MSSQL jdbc driver on jdbc extensions images.

templates/rhpam75-authoring-ha.yaml, templates/rhpam75-authoring.yaml, templates/rhpam75-trial-ephemeral.yaml
See:
https://issues.jboss.org/browse/KIECLOUD-160
=> KIECLOUD-160 removing git ports

templates/contrib/jdbc/modules/kie-custom-jdbc-driver/base-module.yaml
[KIECLOUD-300] rhdm and rhpam standalone modules missing version
https://issues.jboss.org/browse/KIECLOUD-300
=> [KIECLOUD-300] rhdm and rhpam standalone modules missing version

templates/rhpam75-authoring-ha.yaml, templates/rhpam75-authoring.yaml, templates/rhpam75-kieserver-externaldb.yaml, templates/rhpam75-kieserver-mysql.yaml, templates/rhpam75-kieserver-postgresql.yaml, templates/rhpam75-managed.yaml, templates/rhpam75-prod-immutable-kieserver-amq.yaml, templates/rhpam75-prod-immutable-kieserver.yaml, templates/rhpam75-prod-immutable-monitor.yaml, templates/rhpam75-prod.yaml, templates/rhpam75-trial-ephemeral.yaml
https://issues.jboss.org/browse/KIECLOUD-276
@errantepiphany Can you please take a look?
=> [KIECLOUD-276] Adjust readiness probe parameters

templates/rhpam75-authoring-ha.yaml, templates/rhpam75-authoring.yaml, templates/rhpam75-managed.yaml, templates/rhpam75-prod-immutable-monitor.yaml, templates/rhpam75-prod.yaml
[RHPAM-2282] Changes in users and roles made by Business central are not persisted
https://issues.jboss.org/browse/RHPAM-2282
=> [RHPAM-2282] Changes in users and roles made by Business central are not persisted

templates/rhpam75-prod-immutable-kieserver-amq.yaml, templates/rhpam75-prod-immutable-kieserver.yaml
[BAPL-1262] [Field-RFE] OpenShift - Smart Router container resolver for aliases
https://issues.jboss.org/browse/BAPL-1262
=> [BAPL-1262] [Field-RFE] OpenShift - Smart Router container resolver for aliases

templates/rhpam75-prod.yaml
[RHPAM-2314] Strategy and Access Mode corrections
https://issues.jboss.org/browse/RHPAM-2314
=> [RHPAM-2314] Strategy and Access Mode corrections

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3
https://issues.jboss.org/browse/KIECLOUD-313
=> [KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3

templates/rhpam75-prod-immutable-kieserver-amq.yaml
=> Update AMQ image version for kieserver jms integration

templates/contrib/jdbc/README.md
=> KIECLOUD-324-7.5.x] - inform latest supported/tested cekit version

templates/docs/rhpam75-kieserver-mysql.adoc, templates/docs/rhpam75-kieserver-postgresql.adoc, templates/docs/rhpam75-trial-ephemeral.adoc
=> [ADOCS_REGEN] regenerate adocs per recent changes

businesscentral-monitoring/image.yaml, businesscentral-monitoring/osbs-extra/gating.yaml, businesscentral/image.yaml, businesscentral/osbs-extra/gating.yaml, controller/image.yaml, controller/osbs-extra/gating.yaml, kieserver/image.yaml, kieserver/osbs-extra/gating.yaml, smartrouter/image.yaml, smartrouter/osbs-extra/gating.yaml
=> [7.5.x] Adding gating.yaml file for CVP to be persisted in dist-git repo

businesscentral-monitoring/image.yaml, businesscentral-monitoring/osbs-extra/gating.yaml, businesscentral/image.yaml, businesscentral/osbs-extra/gating.yaml, controller/image.yaml, controller/osbs-extra/gating.yaml, kieserver/image.yaml, kieserver/osbs-extra/gating.yaml, smartrouter/image.yaml, smartrouter/osbs-extra/gating.yaml
=> Adding gating.yaml file for CVP to be persisted in dist-git repo

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral/artifact-overrides.yaml, businesscentral/image.yaml, controller/artifact-overrides.yaml, controller/image.yaml, kieserver/artifact-overrides.yaml, kieserver/image.yaml, smartrouter/image.yaml
[KIECLOUD-328] required changes to build meta information for CPaaS
https://issues.jboss.org/browse/KIECLOUD-328
=> [KIECLOUD-328] required changes to build meta information for CPaaS

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver-amq.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod-immutable-monitor.yaml, templates/rhpam76-prod.yaml
=> [RHPAM-2401] - Change strategy to type Rolling for other BA components

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-authoring.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-monitor.yaml, templates/rhpam76-prod.yaml, templates/rhpam76-trial-ephemeral.yaml
=> [AF-2240] Modify haproxy timeout in the template

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml, templates/rhpam76-authoring-ha.yaml, templates/rhpam76-authoring.yaml, templates/rhpam76-kieserver-externaldb.yaml, templates/rhpam76-kieserver-mysql.yaml, templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver-amq.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod-immutable-monitor.yaml, templates/rhpam76-prod.yaml, templates/rhpam76-trial-ephemeral.yaml
[KIECLOUD-332] image naming convention changes
https://issues.jboss.org/browse/KIECLOUD-332
=> [KIECLOUD-332] image naming convention changes

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-prod-immutable-kieserver-amq.yaml
=> [RHPAM-2279] - update amq and datagrid images

templates/rhpam76-authoring.yaml
=> [RHPAM-2314] - Strategy and Access Mode corrections

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-kieserver-mysql.yaml, templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod.yaml
[RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig causing issues when starting pod
See: https://issues.jboss.org/browse/RHPAM-2431
=> [RHPAM-2431] - Busybox dependency in Kieserver DeploymentConfig

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, quickstarts/library-process/README.md, rhpam75-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/contrib/jdbc/image.yaml, templates/contrib/jdbc/modules/kie-custom-jdbc-driver/base-module.yaml, templates/rhpam75-authoring-ha.yaml, templates/rhpam75-authoring.yaml, templates/rhpam75-kieserver-externaldb.yaml, templates/rhpam75-kieserver-mysql.yaml, templates/rhpam75-kieserver-postgresql.yaml, templates/rhpam75-managed.yaml, templates/rhpam75-prod-immutable-kieserver-amq.yaml, templates/rhpam75-prod-immutable-kieserver.yaml, templates/rhpam75-prod-immutable-monitor.yaml, templates/rhpam75-prod.yaml, templates/rhpam75-trial-ephemeral.yaml
[KIECLOUD-335] Upgrade RHDM and RHPAM cloud images to 7.5.1
https://issues.jboss.org/browse/KIECLOUD-335
=> [KIECLOUD-335] Upgrade RHDM and RHPAM cloud images to 7.5.1

rhpam76-image-streams.yaml
Fix https://issues.jboss.org/browse/RHPAM-2311
=> [RHPAM-2311] Add process-migration imageStream

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[KIECLOUD-337] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.4
https://issues.jboss.org/browse/KIECLOUD-337
=> [KIECLOUD-337] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.4

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-authoring.yaml, templates/rhpam76-kieserver-externaldb.yaml, templates/rhpam76-kieserver-mysql.yaml, templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver-amq.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod-immutable-monitor.yaml, templates/rhpam76-prod.yaml, templates/rhpam76-trial-ephemeral.yaml
https://issues.jboss.org/browse/KIECLOUD-346
=> [KIECLOUD-346] username to user name  and typo fix - 7.6.x

templates/rhpam77-authoring-ha.yaml, templates/rhpam77-authoring.yaml, templates/rhpam77-kieserver-externaldb.yaml, templates/rhpam77-kieserver-mysql.yaml, templates/rhpam77-kieserver-postgresql.yaml, templates/rhpam77-managed.yaml, templates/rhpam77-prod-immutable-kieserver-amq.yaml, templates/rhpam77-prod-immutable-kieserver.yaml, templates/rhpam77-prod-immutable-monitor.yaml, templates/rhpam77-prod.yaml, templates/rhpam77-trial-ephemeral.yaml
https://issues.jboss.org/browse/KIECLOUD-346
=> [KIECLOUD-346] username to user name and typo fix

templates/docs/rhpam76-authoring-ha.adoc, templates/docs/rhpam76-authoring.adoc, templates/docs/rhpam76-kieserver-externaldb.adoc, templates/docs/rhpam76-kieserver-mysql.adoc, templates/docs/rhpam76-kieserver-postgresql.adoc, templates/docs/rhpam76-managed.adoc, templates/docs/rhpam76-prod-immutable-kieserver-amq.adoc, templates/docs/rhpam76-prod-immutable-kieserver.adoc, templates/docs/rhpam76-prod-immutable-monitor.adoc, templates/docs/rhpam76-prod.adoc, templates/docs/rhpam76-trial-ephemeral.adoc
=> [KIECLOUD-347] - Re-generated adocs files for branch 7.6.x

templates/rhpam77-kieserver-postgresql.yaml, templates/rhpam77-managed.yaml, templates/rhpam77-prod-immutable-kieserver-amq.yaml, templates/rhpam77-prod-immutable-kieserver.yaml, templates/rhpam77-prod.yaml
=> [RHPAM-2401-1] - QE review, db is not ba component 

templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver-amq.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod.yaml
=> [RHPAM-2401-1] - QE review, db is not ba component

templates/rhpam76-authoring-ha.yaml, templates/rhpam76-kieserver-mysql.yaml, templates/rhpam76-kieserver-postgresql.yaml, templates/rhpam76-managed.yaml, templates/rhpam76-prod-immutable-kieserver.yaml, templates/rhpam76-prod.yaml
Cherry pick of #395 to the 7.6.x branch
See: [https://issues.redhat.com/browse/RHPAM-2431](https://issues.redhat.com/browse/RHPAM-2431)
=> [7.6.x] [RHPAM-2431] Add registry url for ose-cli image

templates/rhpam77-authoring-ha.yaml, templates/rhpam77-kieserver-mysql.yaml, templates/rhpam77-kieserver-postgresql.yaml, templates/rhpam77-managed.yaml, templates/rhpam77-prod-immutable-kieserver.yaml, templates/rhpam77-prod.yaml
See: [https://issues.redhat.com/browse/RHPAM-2431](https://issues.redhat.com/browse/RHPAM-2431)
=> [RHPAM-2431] Add registry url for ose-cli image

templates/rhpam76-authoring-ha.yaml
Cherry pick #401 to master branch
See: https://issues.redhat.com/browse/RHPAM-2615
=> [RHPAM-2615] Increase memory limit for BC in Authoring HA

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[KIECLOUD-355] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.6
https://issues.redhat.com/browse/KIECLOUD-355
=> [KIECLOUD-355] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.6

templates/docs/rhpam77-authoring-ha.adoc, templates/docs/rhpam77-authoring.adoc, templates/rhpam77-authoring-ha.yaml, templates/rhpam77-authoring.yaml
Related JIRA
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2567
=> [RHPAM-2567] Remove ReadWriteMany requirement from non-HA Authoring environment and switch all Authoring templates to Controller strategy

templates/rhpam77-prod-immutable-kieserver-amq.yaml
=> Correct description fields for signal JMS parameters

templates/rhpam77-authoring-ha.yaml
=> Fix authoring ha RHPAMCENTR user place in deployment config

templates/rhpam77-prod.yaml
JIRA: https://issues.redhat.com/browse/RHPAM-2706
=> [RHPAM-2706] Smart router cannot connect to controller

templates/rhpam77-authoring-ha.yaml, templates/rhpam77-authoring.yaml, templates/rhpam77-kieserver-externaldb.yaml, templates/rhpam77-kieserver-mysql.yaml, templates/rhpam77-kieserver-postgresql.yaml, templates/rhpam77-managed.yaml, templates/rhpam77-prod-immutable-kieserver-amq.yaml, templates/rhpam77-prod-immutable-kieserver.yaml, templates/rhpam77-prod-immutable-monitor.yaml, templates/rhpam77-prod.yaml, templates/rhpam77-trial-ephemeral.yaml
=> [BXMSDOC-5159] Template editorial changes

templates/rhpam77-authoring-ha.yaml, templates/rhpam77-authoring.yaml
=> [RHPAM-2732] Kie Server is not connected to BC in Authoring template

templates/rhpam78-authoring-ha.yaml, templates/rhpam78-prod-immutable-kieserver-amq.yaml
=> [KIECLOUD-378] - Increase AMQ broker version to 7.6

templates/rhpam77-authoring-ha.yaml
=> [RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5

process-migration/image.yaml
Fiix https://issues.redhat.com/browse/RHPAM-2576
=> [RHPAM-2576] Set package manager

templates/docs/rhpam78-authoring-ha.adoc, templates/rhpam78-authoring-ha.yaml
=> RHPAM-2833: Allow to configure replicas in Authoring HA

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/library-process/README.md, rhpam77-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/contrib/jdbc/image.yaml, templates/contrib/jdbc/modules/kie-custom-jdbc-driver/base-module.yaml, templates/rhpam77-authoring-ha.yaml, templates/rhpam77-authoring.yaml, templates/rhpam77-kieserver-externaldb.yaml, templates/rhpam77-kieserver-mysql.yaml, templates/rhpam77-kieserver-postgresql.yaml, templates/rhpam77-managed.yaml, templates/rhpam77-prod-immutable-kieserver-amq.yaml, templates/rhpam77-prod-immutable-kieserver.yaml, templates/rhpam77-prod-immutable-monitor.yaml, templates/rhpam77-prod.yaml, templates/rhpam77-trial-ephemeral.yaml
=> [KIECLOUD-389] - Prepare RHPAM and RHDM repositories for 7.7.1 release

templates/contrib/jdbc/Makefile, templates/contrib/jdbc/README.md
=> [RHPAM-2948] - Unable to create custom image for Database

templates/contrib/jdbc/Makefile, templates/contrib/jdbc/README.md, templates/contrib/jdbc/prepare.sh, templates/contrib/jdbc/tests/features/sybase-feature.prepare
=> [RHPAM-2969] - Custom Database Image for Sybase not working

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/branch-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
=> [KIECLOUD-377] - Increase EAP in OpenShift images to 7.3.0

templates/contrib/jdbc/README.md
JIRA: https://issues.redhat.com/browse/RHPAM-2976
Description: Update the table of supported databases.
=> RHPAM-2976 Update table

templates/rhpam78-kieserver-externaldb.yaml, templates/rhpam78-kieserver-mysql.yaml, templates/rhpam78-kieserver-postgresql.yaml
=> [KIECLOUD-401] removing mandatory marker from MAVEN_REPO_URL

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml
=> [KIECLOUD-402] - update repo branch

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
=> [RHPAM-3016] - Rebuild new 7.7.1 images with EAP 7.2.9

templates/docs/README.adoc, templates/docs/rhpam79-authoring-ha.adoc, templates/docs/rhpam79-authoring.adoc, templates/docs/rhpam79-kieserver-externaldb.adoc, templates/docs/rhpam79-kieserver-mysql.adoc, templates/docs/rhpam79-kieserver-postgresql.adoc, templates/docs/rhpam79-managed.adoc, templates/docs/rhpam79-prod-immutable-kieserver-amq.adoc, templates/docs/rhpam79-prod-immutable-kieserver.adoc, templates/docs/rhpam79-prod-immutable-monitor.adoc, templates/docs/rhpam79-prod.adoc, templates/docs/rhpam79-trial-ephemeral.adoc
=> [KIECLOUD-411] - Update adocs

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
=> [RHPAM-3020] - Update EAP version from 7.3.1 to 7.3.2 on PAM/DM 7.8.x

templates/rhpam79-authoring-ha.yaml
=> [KIECLOUD-414] - Increase DataGrid 7.3 image tag version to 1.6

quickstarts/router-ext/README.md, quickstarts/router-ext/pom.xml, quickstarts/router-ext/src/main/java/org/kie/server/demo/ByPassUserNotAllowedRestrictionPolicy.java, quickstarts/router-ext/src/main/java/org/kie/server/demo/InMemoryConfigRepository.java, quickstarts/router-ext/src/main/java/org/kie/server/demo/LatestVersionContainerResolver.java, quickstarts/router-ext/src/main/resources/META-INF/services/org.kie.server.router.spi.ConfigRepository, quickstarts/router-ext/src/main/resources/META-INF/services/org.kie.server.router.spi.ContainerResolver, quickstarts/router-ext/src/main/resources/META-INF/services/org.kie.server.router.spi.RestrictionPolicy
=> [KIECLOUD-421] - Provide an smartrouter extension app example

businesscentral-monitoring/tag-overrides.yaml, businesscentral/tag-overrides.yaml, controller/tag-overrides.yaml, kieserver/tag-overrides.yaml, process-migration/tag-overrides.yaml, smartrouter/tag-overrides.yaml
=> [KIECLOUD-431] - Prepare branch 7.8.x for new tag 7.8.1.GA-1

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml, templates/docs/README.adoc, templates/docs/rhpam79-authoring-ha.adoc, templates/docs/rhpam79-authoring.adoc, templates/docs/rhpam79-kieserver-externaldb.adoc, templates/docs/rhpam79-kieserver-mysql.adoc, templates/docs/rhpam79-kieserver-postgresql.adoc, templates/docs/rhpam79-managed.adoc, templates/docs/rhpam79-prod-immutable-kieserver-amq.adoc, templates/docs/rhpam79-prod-immutable-kieserver.adoc, templates/docs/rhpam79-prod-immutable-monitor.adoc, templates/docs/rhpam79-prod.adoc, templates/docs/rhpam79-trial-ephemeral.adoc
=> [KIECLOUD-441] - Prepare RHPAM and RHDM repositories for 7.9.0 release

templates/rhpam710-authoring-ha.yaml, templates/rhpam710-authoring.yaml, templates/rhpam710-kieserver-externaldb.yaml, templates/rhpam710-kieserver-mysql.yaml, templates/rhpam710-kieserver-postgresql.yaml, templates/rhpam710-managed.yaml, templates/rhpam710-prod-immutable-kieserver-amq.yaml, templates/rhpam710-prod-immutable-kieserver.yaml, templates/rhpam710-prod-immutable-monitor.yaml, templates/rhpam710-prod.yaml, templates/rhpam710-trial-ephemeral.yaml
=> [BXMSDOC-6663] Editorial change - add comma

templates/rhpam710-authoring-ha.yaml, templates/rhpam710-authoring.yaml, templates/rhpam710-kieserver-externaldb.yaml, templates/rhpam710-kieserver-mysql.yaml, templates/rhpam710-kieserver-postgresql.yaml, templates/rhpam710-managed.yaml, templates/rhpam710-prod-immutable-kieserver-amq.yaml, templates/rhpam710-prod-immutable-kieserver.yaml, templates/rhpam710-prod-immutable-monitor.yaml, templates/rhpam710-prod.yaml, templates/rhpam710-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/RHPAM-3245
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> [RHPAM-3245] - Change resource requirements for BC and KIE Server

smartrouter/image.yaml
https://issues.redhat.com/browse/RHPAM-3273
@jakubschwan @spolti
=> [RHPAM-3273] Fix example for LOG_LEVEL in SmartRouter image

.circleci/config.yml, dashbuilder/README.adoc, dashbuilder/artifact-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/container.yaml, dashbuilder/content_sets.yml, dashbuilder/image.yaml, dashbuilder/osbs-extra/gating.yaml, dashbuilder/tag-overrides.yaml
=> [AF-2626] - Create Dashbuilder Runtime Image

businesscentral/image.yaml
See: https://issues.redhat.com/browse/RHPAM-3299
=> [RHPAM-3299] - BC image not using PV to store its local .m2/repository

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
=> [RHPAM-3099] - Update EAP version from 7.3.3 on PAM/DM 7.9.x

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
=> [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files

quickstarts/library-process/README.md, templates/rhpam710-authoring-ha.yaml, templates/rhpam710-prod-immutable-kieserver-amq.yaml
=> [KIECLOUD-474] - Increase AMQ broker version to 7.8

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHPAM-3283
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> [RHPAM-3283] - Align the RHPAM modules with JBoss EAP modules 7.3.x branch

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/artifact-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHPAM-3322
=> [RHPAM-3322] - Update EAP version from 7.3.4 on PAM/DM 7.10.x

templates/rhpam710-authoring-ha.yaml, templates/rhpam710-authoring.yaml, templates/rhpam710-kieserver-externaldb.yaml, templates/rhpam710-kieserver-mysql.yaml, templates/rhpam710-kieserver-postgresql.yaml, templates/rhpam710-managed.yaml, templates/rhpam710-prod-immutable-kieserver-amq.yaml, templates/rhpam710-prod-immutable-kieserver.yaml, templates/rhpam710-prod-immutable-monitor.yaml, templates/rhpam710-prod.yaml, templates/rhpam710-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/KIECLOUD-480
Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>
=> [KIECLOUD-480] - Allowing value flag as "optional" for LdapExtended login module

rhpam710-image-streams.yaml
See: https://issues.redhat.com/browse/KIECLOUD-486
=> [KIECLOUD-486] - Add dashbuilder image is not listed on the imagestreams file

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, dashbuilder/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml
=> [KIECLOUD-487] - update branch overrides to 7.10.x branch

Makefile, README.md
See: https://issues.redhat.com/browse/KIECLOUD-489
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
=> [KIECLOUD-489] - Provide Make command to build rhpam images

kieserver/image.yaml
=> [RHPAM - 3499] - [ONE-OFF](7.9.1) Make pulling of dependencies and kjar validation skippable in kie-server lauch script

templates/rhpam711-prod-immutable-monitor.yaml
See: https://issues.redhat.com/browse/KIECLOUD-509
- [] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`
=> [KIECLOUD-509] - Update RHDM and RHPAM templates' description.

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/artifact-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, quickstarts/library-process/pom.xml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHPAM-3527
=> [RHPAM-3527] - Update EAP version from 7.3.6 on PAM 7.11.x

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-518
=> [KIECLOUD-518] - Update RHSSO EAP adatpers from 7.3.1 to 7.4.5

kieserver/image.yaml
See: https://issues.redhat.com/browse/RHPAM-3330
=> [RHPAM-3330] Operator/Image support for Kie-Server Cluster support

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, dashbuilder/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml
=> Update branch-overrides.yaml to match 7.11.x branch.

README.md, templates/docs/README.adoc
=> adocs update

templates/rhpam712-kieserver-mysql.yaml, templates/rhpam712-kieserver-postgresql.yaml, templates/rhpam712-managed.yaml, templates/rhpam712-trial-ephemeral.yaml
=> [KIECLOUD-275] - Remove database related tags from templates

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml
=> [KIECLOUD-532] JDBC driver on RHDM/RHPAM images

.circleci/config.yml
See:https://issues.redhat.com/browse/KIECLOUD-542
=> [KIECLOUD-542] Conscious Language on KieCloud repos 7.11.x

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml
(cherry picked from commit dac1dfd62610c69975453f41432155fb65acd591)
See:https://issues.redhat.com/browse/KIECLOUD-532
=> [KIECLOUD-532] JDBC driver on RHDM/RHPAM images (#541)

templates/contrib/jdbc/cekit/image.yaml
=> use latest bash image on the example extension images

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, process-migration/branch-overrides.yaml, process-migration/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
[KIECLOUD-553] - Adjust permissions on openshift-layer module on cct_module
=> [KIECLOUD-553] - update cct_module tag to 0.39.4

templates/rhpam712-authoring-ha.yaml
[KIECLOUD-564] 7.12 Checkpoint - Increase JDG version to 8.x
https://issues.redhat.com/browse/KIECLOUD-564
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
=> [KIECLOUD-564] 7.12 Checkpoint - Increase JDG version to 8.x

.github/bot-files/reviewers.yml
Updated Reviewers file to include amadhusu
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
=> Update Reviewers to include amadhusu

businesscentral-monitoring/artifact-overrides.yaml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/artifact-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/artifact-overrides.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/artifact-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/artifact-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-562
=> [KIECLOUD-562] - Upgrade EAP to 7.4.0 on RHDM and RHPAM images

templates/contrib/jdbc/cekit/README.md
See: https://issues.redhat.com/browse/BXMSDOC-8174
- [] Pull Request title is properly formatted: `[RHPAM-XYZ] Subject`
=> use cekit 3.11 or higher

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-583
=> [KIECLOUD-583] - Upgrade EAP to 7.4.1 on RHDM and RHPAM images

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-565
=> [KIECLOUD-565] - Update RHSSO EAP adatpers from 7.4.5 to 7.5.0

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-544
=> [KIECLOUD-544] - Combine the prometheus agent and config modules

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
See https://issues.redhat.com/browse/KIECLOUD-594
=> [KIECLOUD-594] Migrate the access_log_valve script to wildfly-cekit-modules

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml
See:https://issues.redhat.com/browse/KIECLOUD-578
=> [KIECLOUD-578]

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml
See:https://issues.redhat.com/browse/KIECLOUD-578
=> [KIECLOUD-578] Upgrade wildfly-cekit-modules to include Keycloak support for SSO 7.5

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-505
=> [KIECLOUD-505] Update https.sh script to use the one provided by wildfly-cekit-modules

businesscentral/image.yaml, templates/rhpam712-authoring-ha.yaml
WORK IN PROGRESS
See: https://issues.redhat.com/browse/RHPAM-4064
=> [RHPAM-4064] BC HA does not start because of outdated configuration

templates/rhpam713-authoring-ha.yaml, templates/rhpam713-authoring.yaml, templates/rhpam713-kieserver-externaldb.yaml, templates/rhpam713-kieserver-mysql.yaml, templates/rhpam713-kieserver-postgresql.yaml, templates/rhpam713-managed.yaml, templates/rhpam713-prod-immutable-kieserver-amq.yaml, templates/rhpam713-prod-immutable-kieserver.yaml, templates/rhpam713-prod-immutable-monitor.yaml, templates/rhpam713-prod.yaml, templates/rhpam713-trial-ephemeral.yaml
=> docs review - capitalize all ldap occurrencies

templates/rhpam713-authoring-ha.yaml, templates/rhpam713-authoring.yaml, templates/rhpam713-kieserver-externaldb.yaml, templates/rhpam713-kieserver-mysql.yaml, templates/rhpam713-kieserver-postgresql.yaml, templates/rhpam713-managed.yaml, templates/rhpam713-prod-immutable-kieserver-amq.yaml, templates/rhpam713-prod-immutable-kieserver.yaml, templates/rhpam713-prod-immutable-monitor.yaml, templates/rhpam713-prod.yaml, templates/rhpam713-trial-ephemeral.yaml
Cherry-picks https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/586
=> fix small typo on ldap keep non mapped roles

quickstarts/post-configure-example/README.md
=> [KIECLOUD-610] - Provide a quickstart about how to add new users on EAP

templates/docs/rhpam712-authoring-ha.adoc, templates/docs/rhpam712-authoring.adoc, templates/docs/rhpam712-kieserver-externaldb.adoc, templates/docs/rhpam712-kieserver-mysql.adoc, templates/docs/rhpam712-kieserver-postgresql.adoc, templates/docs/rhpam712-managed.adoc, templates/docs/rhpam712-prod-immutable-kieserver-amq.adoc, templates/docs/rhpam712-prod-immutable-kieserver.adoc, templates/docs/rhpam712-prod-immutable-monitor.adoc, templates/docs/rhpam712-prod.adoc, templates/docs/rhpam712-trial-ephemeral.adoc
See: https://issues.redhat.com/browse/KIECLOUD-614
=> update adocs due KIECLOUD-614

templates/rhpam712-authoring-ha.yaml
See: https://issues.redhat.com/browse/RHPAM-4109
=> [RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer

templates/rhpam713-authoring-ha.yaml
See:https://issues.redhat.com/browse/RHPAM-4109
=> RHPAM-4109 Cannot open created project - FileSystem Index fails - NullPointerException

templates/docs/rhpam712-authoring-ha.adoc
=> update templates' adoc

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
(cherry picked from commit 4a73630fb1d0ecf97a7573f23361fffe1fb20391)
See: https://issues.redhat.com/browse/KIECLOUD-594
=> [KIECLOUD-594] 7.12.x Migrate the access_log_valve script to wildfly-cekit-modules 

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml
(cherry picked from commit ee73bec905233e292b2c102402b2fe4a77dae262)
See:https://issues.redhat.com/browse/KIECLOUD-505
=> [KIECLOUD-505] 7.12.x Update https.sh script to use the one provided by wildfly-cekit-modules

quickstarts/post-configure-example/README.md
=> [RHPAM-4146] - [ELYTRON] Authorization fails when using role mapping

quickstarts/hello-rules-multi-module/README.md, quickstarts/hello-rules-multi-module/hellorules-model/pom.xml, quickstarts/hello-rules-multi-module/hellorules-model/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/Greeting.java, quickstarts/hello-rules-multi-module/hellorules-model/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/Person.java, quickstarts/hello-rules-multi-module/hellorules/pom.xml, quickstarts/hello-rules-multi-module/hellorules/src/main/resources/META-INF/kmodule.xml, quickstarts/hello-rules-multi-module/hellorules/src/main/resources/META-INF/org/openshift/quickstarts/rhpam/kie-server/decisions/HelloRules.drl, quickstarts/hello-rules-multi-module/pom.xml, quickstarts/hello-rules/README.md, quickstarts/hello-rules/hellorules-client/pom.xml, quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/client/HelloRulesCallback.java, quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/client/HelloRulesClient.java, quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/client/HelloRulesServlet.java, quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/jboss-web.xml, quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/web.xml, quickstarts/hello-rules/hellorules-client/src/test/java/org/openshift/quickstarts/rhpam/kieserver/decisions/client/HelloRulesTest.java, quickstarts/hello-rules/hellorules/pom.xml, quickstarts/hello-rules/hellorules/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/Greeting.java, quickstarts/hello-rules/hellorules/src/main/java/org/openshift/quickstarts/rhpam/kieserver/decisions/Person.java, quickstarts/hello-rules/hellorules/src/main/resources/META-INF/kmodule.xml, quickstarts/hello-rules/hellorules/src/main/resources/META-INF/org/openshift/quickstarts/rhdm/kie-server/hellorules/HelloRules.drl, quickstarts/hello-rules/pom.xml, quickstarts/router-ext/pom.xml
- This commit add ths decisions quickstarts from rhdm-7-openshift
repository
- renamig from rhdm to rhpam
See: https://issues.redhat.com/browse/KIECLOUD-604
=> [KIECLOUD-604] - Move RHDM templates and quickstarts to RHPAM repository

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, rhpam712-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/rhpam712-authoring-ha.yaml, templates/rhpam712-authoring.yaml, templates/rhpam712-kieserver-externaldb.yaml, templates/rhpam712-kieserver-mysql.yaml, templates/rhpam712-kieserver-postgresql.yaml, templates/rhpam712-managed.yaml, templates/rhpam712-prod-immutable-kieserver-amq.yaml, templates/rhpam712-prod-immutable-kieserver.yaml, templates/rhpam712-prod-immutable-monitor.yaml, templates/rhpam712-prod.yaml, templates/rhpam712-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/KIECLOUD-620
=> [KIECLOUD-620] - Prepare RHDM and RHPAM repositories for 7.12.1 release

.circleci/config.yml
See: https://issues.redhat.com/browse/KIECLOUD-624
=> [KIECLOUD-624] - use validator tool from 7.12.x branch

businesscentral/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-228
igned-off-by: desmax74 <mdessi@redhat.com>
=> [KIECLOUD-228] Hide ISPN logs

scripts/generate-adocs.sh, templates/decision/rhdm713-prod-immutable-kieserver-amq.yaml, templates/decision/rhdm713-prod-immutable-kieserver.yaml, templates/docs/decision/rhdm713-prod-immutable-kieserver-amq.adoc, templates/docs/decision/rhdm713-prod-immutable-kieserver.adoc
=> [KIECLOUD-628] - Update rhdm quickstarts references on operator

kieserver/image.yaml
=> [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image

kieserver/image.yaml
See: https://issues.redhat.com/browse/RHPAM-3528
(cherry picked from commit dcc8ab1e9c652afc841a5d4d1643314ad67ed885)
=> [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image (#613)

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, process-migration/branch-overrides.yaml, process-migration/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-625
=> [KIECLOUD-625] - Upgrade EAP to 7.4 latest cp patch on RHPAM images

templates/decision/rhdm713-authoring-ha.yaml, templates/docs/decision/rhdm713-authoring-ha.adoc, templates/docs/process/rhpam713-authoring-ha.adoc, templates/process/rhpam713-authoring-ha.yaml
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
See: https://issues.redhat.com/browse/KIECLOUD-627
[DataGrid8 images](https://catalog.redhat.com/software/containers/datagrid/datagrid-8-rhel8/5d53e7b4d70cc5521d20ecea?tag=all)
=> [KIECLOUD-627] 7.13 Checkpoint - Increase JDG version to 8.3.3

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-635
=> [KIECLOUD-635] - Update eap on rhpam images to 7.4.4.CR2

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, dashbuilder/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml
Signed-off-by: Davide Salerno <dsalerno@redhat.com>
See: https://issues.redhat.com/browse/RHPAM-4279
=> [RHPAM-4279] Build RHPAM 7.13.0 Images

templates/decision/rhdm713-authoring-ha.yaml, templates/process/rhpam713-authoring-ha.yaml
Reverto Infinispan to a working version
See:https://issues.redhat.com/browse/KIECLOUD-634
=>  [KIECLOUD-634] Revert used RHDG version to 8.1

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
=> osbs requires the com.redhat.component label

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
=> component must be a valid brew package, reverting back to previous

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
=> [7.13.x-blue] update brew packages name, repositories names and branches

templates/process/rhpam713-kieserver-postgresql.yaml
=> [RHPAM-4439] Vulnerable Version Of PostgreSQL Found

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHPAM-4481
=> [RHPAM-4481] - Update EAP version to 7.4.6 on RHPAM Images

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, ibm-bamoe8-image-streams.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, scripts/update-version.py, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
=> [KIECLOUD-653] - Update 7.13.x-blue branch for 8.0.1 release

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, rhpam713-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
=> [KIECLOUD-653] - Update 7.13.x branch for 7.13.1 release

templates/process/rhpam714-kieserver-postgresql.yaml, templates/process/rhpam714-managed.yaml, templates/process/rhpam714-prod-immutable-kieserver-amq.yaml, templates/process/rhpam714-prod-immutable-kieserver.yaml, templates/process/rhpam714-prod.yaml
See:https://issues.redhat.com/browse/RHPAM-4464
=> [RHPAM-4464]-PostgreSQL 13 Pod won't start due to version 10 data directory

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
See https://issues.redhat.com/browse/RHPAM-4616
Cherry-picks https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/657
=> [RHPAM-4616] - Update EAP version to 7.4.8 on RHPAM/BAMOE Images

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, rhpam713-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
=> [KIECLOUD-656] - Prepare RHPAM branches for 7.13.2

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, ibm-bamoe8-image-streams.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, scripts/update-version.py, smartrouter/image.yaml, smartrouter/tag-overrides.yaml, templates/contrib/jdbc/cekit/image.yaml, templates/contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml
=> [KIECLOUD-656] - Prepare BAMOE branches for 8.0.2

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
Jira: https://issues.redhat.com/browse/KIECLOUD-672
This module will update all the packages in the image to avoid having old packages. Related to RHELDST-15034
=> [7.13.x-blue][KIECLOUD-672] add pkg-update module

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
Jira: https://issues.redhat.com/browse/KIECLOUD-672
This module will update all the packages in the image to avoid having old packages. Related to RHELDST-15034
=> [7.13.x][KIECLOUD-672] add pkg-update module

businesscentral-monitoring/image.yaml, businesscentral/image.yaml, controller/image.yaml, dashbuilder/image.yaml, kieserver/image.yaml, process-migration/image.yaml, smartrouter/image.yaml
Jira: https://issues.redhat.com/browse/KIECLOUD-672
This module will update all the packages in the image to avoid having old packages. Related to RHELDST-15034
=> [KIECLOUD-672] add pkg-update module

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, rhpam713-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
Signed-off-by: Your Name <fspolti@redhat.com>
=> [KIECLOUD-682] - Prepare RHPAM repositories for 7.13.3

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, contrib/jdbc/cekit/image.yaml, contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, ibm-bamoe8-image-streams.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/router-ext/README.md, scripts/update-version.py, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
Signed-off-by: Your Name <fspolti@redhat.com>
=> [KIECLOUD-687] - Prepare the BAMOE branches for the 8.0.3 release

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
Cherry picks https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/667
=> x[RHPAM-4666] - Update JBoss EAP to 7.4.10 on RHPAM and BAMOE images

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
Cherry picks https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/667
=> [RHPAM-4666] - Update JBoss EAP to 7.4.10 on RHPAM and BAMOE images

quickstarts/hello-rules/hellorules/pom.xml
=> change the maven red hat repo urls from http to https (#670)

scripts/check-image-version.sh
Cherry-picks https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/674,
---------
=> [KIECLOUD-700] - Verify the version of the binaries on the built images

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, contrib/jdbc/cekit/image.yaml, contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, ibm-bamoe8-image-streams.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/library-process/README.md, quickstarts/router-ext/README.md, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-724
=> [KIECLOUD-724] - Prepare BAMOE next branch for 8.0.4

businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/library-process/README.md, quickstarts/router-ext/README.md, rhpam713-image-streams.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-724
=> [KIECLOUD-724] - Prepare RHPAM next branch for 7.13.4

businesscentral-monitoring/branch-overrides.yaml, businesscentral/branch-overrides.yaml, controller/branch-overrides.yaml, dashbuilder/branch-overrides.yaml, kieserver/branch-overrides.yaml, process-migration/branch-overrides.yaml, smartrouter/branch-overrides.yaml
=> update branch in the branch-overides descriptors

businesscentral-monitoring/tag-overrides.yaml, businesscentral/tag-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/tag-overrides.yaml, process-migration/tag-overrides.yaml, quickstarts/hello-rules-multi-module/README.md, quickstarts/hello-rules/README.md, quickstarts/library-process/README.md, quickstarts/router-ext/README.md, smartrouter/tag-overrides.yaml
=> [KIECLOUD-728] - Prepare RHPAM and BAMOE 7.13.3 images for respin

businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/tag-overrides.yaml, controller/branch-overrides.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/tag-overrides.yaml, kieserver/branch-overrides.yaml, kieserver/tag-overrides.yaml, smartrouter/branch-overrides.yaml, smartrouter/tag-overrides.yaml
=> [RHPAM-4762] - Upgrade JBoss EAP to 7.4.12 on RHPAM and BAMOE images

quickstarts/hello-rules-multi-module/pom.xml, quickstarts/hello-rules/hellorules/pom.xml, quickstarts/hello-rules/pom.xml, quickstarts/library-process/library/pom.xml, quickstarts/library-process/pom.xml, quickstarts/router-ext/pom.xml
=> RHPAM-4682

quickstarts/hello-rules/hellorules/pom.xml, quickstarts/hello-rules/pom.xml, quickstarts/library-process/library/pom.xml, quickstarts/library-process/pom.xml, quickstarts/router-ext/pom.xml
=> [KIECLOUD-734] - Resolve conflicts in quickstarts pom xml files

.github/bot-files/reviewers.yml, businesscentral-monitoring/branch-overrides.yaml, businesscentral-monitoring/image.yaml, businesscentral-monitoring/tag-overrides.yaml, businesscentral/branch-overrides.yaml, businesscentral/image.yaml, businesscentral/tag-overrides.yaml, contrib/jdbc/cekit/image.yaml, contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml, controller/branch-overrides.yaml, controller/image.yaml, controller/tag-overrides.yaml, dashbuilder/branch-overrides.yaml, dashbuilder/image.yaml, dashbuilder/tag-overrides.yaml, ibm-bamoe8-image-streams.yaml, kieserver/branch-overrides.yaml, kieserver/image.yaml, kieserver/tag-overrides.yaml, process-migration/image.yaml, process-migration/tag-overrides.yaml, quickstarts/hello-rules-multi-module/README.md, quickstarts/hello-rules/README.md, quickstarts/library-process/README.md, quickstarts/router-ext/README.md, scripts/check-image-version.sh, smartrouter/branch-overrides.yaml, smartrouter/image.yaml, smartrouter/tag-overrides.yaml
=> Merge next on release blue

quickstarts/hello-rules-multi-module/pom.xml, quickstarts/hello-rules/hellorules/pom.xml, quickstarts/hello-rules/pom.xml, quickstarts/library-process/library/pom.xml, quickstarts/library-process/pom.xml, quickstarts/router-ext/pom.xml
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/699
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/700
=> [7.13.x-blue-next] Update BAMOE quickstarts with BAMOE 8.0.4 CR2 artifacts

quickstarts/hello-rules-multi-module/pom.xml, quickstarts/hello-rules/hellorules/pom.xml, quickstarts/hello-rules/pom.xml, quickstarts/library-process/library/pom.xml, quickstarts/library-process/pom.xml, quickstarts/router-ext/pom.xml
Related PRs:
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/699
- https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/700
=> [7.13.x-blue] Update BAMOE quickstarts with BAMOE 8.0.4 CR2 artifacts
